stages:
  download:
    cmd: python src/download_data.py
    deps:
      - src/download_data.py
    params:
      - download
    outs:
      - data/raw/combined_stocks.csv

  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/combined_stocks.csv
    params:
      - preprocess
    outs:
      - data/processed/stock_data_cleaned.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/stock_data_cleaned.csv
    params:
      - feature_engineering
    outs:
      - data/features/stock_data_features.csv
    metrics:
      - metrics/data_quality.json:
          cache: false

  split:
    cmd: python src/split_data.py
    deps:
      - src/split_data.py
      - data/features/stock_data_features.csv
    params:
      - split
    outs:
      - data/features/train.csv
      - data/features/test.csv
