# DVC Pipeline Parameters Configuration

# Data Download Configuration
download:
  tickers:
    - AAPL    # Apple Inc.
    - GOOGL   # Alphabet Inc.
    - MSFT    # Microsoft Corporation
    - TSLA    # Tesla Inc.
  start_date: "2020-01-01"
  end_date: "2024-12-31"
  interval: "1d"  # Daily data

# Preprocessing Configuration
preprocess:
  remove_nulls: true
  fill_method: "ffill"  # Forward fill for missing values
  min_data_points: 100  # Minimum data points required per stock

# Feature Engineering Configuration
feature_engineering:
  # Moving Average windows
  ma_window_short: 10
  ma_window_long: 50
  
  # RSI (Relative Strength Index)
  rsi_period: 14
  
  # MACD (Moving Average Convergence Divergence)
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  
  # Bollinger Bands
  bb_window: 20
  bb_std: 2

# Train-Test Split Configuration
split:
  test_size: 0.2
  random_state: 42
  shuffle: false  # Keep time series order
